apiVersion: v1
kind: Secret
metadata:
  name: github-pull-secret
  namespace: slack-integrations
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiVVNFUk5BTUUiLCJwYXNzd29yZCI6IjM5NTc4ZWNlZTBmOWYzY2MxOGIxZjRmMGZkNDViNTU0YTNiMDdmZTIiLCJlbWFpbCI6ImRldm9wc0BkaWdpYmFuay5jby5pbCIsImF1dGgiOiJWVk5GVWs1QlRVVTZNemsxTnpobFkyVmxNR1k1WmpOall6RTRZakZtTkdZd1ptUTBOV0kxTlRSaE0ySXdOMlpsTWc9PSJ9fX0=
type: kubernetes.io/dockerconfigjson