name: build-push-docker-image

on:
  workflow_dispatch:
    inputs:
      dockerfile-path:
        description: path to Dockerfile
        type: string
        required: true
        default: ""
      image-name:
        description: image-name
        type: string
        required: true
        default: ""
      tag:
        description: image-tag
        type: string
        required: true
        default: ""

jobs:
  docker-build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: docker steps
          run: |            
            docker login -u="${{ secrets.DOCKER_USER }}" -p="${{ secrets.DOCKER_PASS }}"
            docker build -t ${{ github.event.inputs.image-name }} ./${{ github.event.inputs.dockerfile-path }}
            docker tag ${{ github.event.inputs.image-name }}:${{ github.event.inputs.tag }} devopzvi/slack:${{ github.event.inputs.image-name }}:${{ github.event.inputs.tag }}
            docker push devopzvi/slack:${{ github.event.inputs.image-name }}:${{ github.event.inputs.tag }}

      
